### ISSUE TITLE
您好，请问一个问题可以吗？

### ISSUE THREAD

**Issue by chanyufog** [chenjiandongx/stackoverflow#1]
请问您的统计作图是通过什么做的？数据存储是否是先保存到本地再读取到数据库中？谢谢

**Comment by chenjiandongx** [comment]
作图大体上用的 tableau 这里的数据我是先保存到本地再导入数据库处理的 因为可能有些数据需要先清理

**Comment by chanyufog** [comment]
谢谢，非常感谢
