### ISSUE TITLE
readme 中可以添加使用方法么？

### ISSUE THREAD

**Issue by macanv** [chenjiandongx/stackoverflow#2]
可否提供main 方法

**Comment by chenjiandongx** [comment]
scrapy 框架要在命令行中运行，没有 main 方法

运行爬虫的方法：
1. cd 到根目录下
2. 执行 ``` scrapy crawl stackoverflow -o xxx.json/csv```  -o 参数为可选项，是将数据保存为本地文件

**Comment by macanv** [comment]
谢谢，已经get.

**Comment by chenjiandongx** [comment]
嗯，那我关闭这个 issue 了
